name = "sbay-leap2026-pressroom"
main = "worker.js"
account_id = "8ba0f8980fb2f466848eb0e13b292e76"
compatibility_date = "2026-08-31"
workers_dev = false
preview_urls = false

routes = [
  { pattern = "leap2026.sbay.sa", custom_domain = true }
]

[assets]
directory = "./docs"
binding = "ASSETS"
not_found_handling = "404-page"
html_handling = "auto-trailing-slash"
